### ISSUE TITLE
player_name not displayed

### ISSUE THREAD

**Issue by logistic94** [Limmek/MStats-for-rust#15]
If player in they steam profile have unique id in personal link, player_name not displayed
-Default steam profle link  teamcommunity.com/profiles/000000000000000000
-With id https://steamcommunity.com/id/sometext/

**Comment by logistic94** [comment]
I think its not problem with steam link, i test and player name display only in eng, in ukr or russian not display

**Comment by Limmek** [comment]
The problem is in [EncodeNonAsciiCharacters](https://github.com/Limmek/MStats-for-rust/blob/b3697f297265892e9ee99a0c506b01a9407e0e5f/MStats.cs#L893) The function only works for english characters and replace all other with an empty one. It is following the [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) standard.
The function should probably be replaced to support non english standard characters like ukr, ru, chinese and so on or just remove it completely.

You could try to remove the encoding then it should work. Just replace all
`EncodeNonAsciiCharacters(player.displayName)` with `player.displayName`
`EncodeNonAsciiCharacters(((BasePlayer)entity).displayName)` with `((BasePlayer)entity).displayName`
`EncodeNonAsciiCharacters(((BasePlayer)player).displayName)` with `((BasePlayer)player).displayName`

**Comment by logistic94** [comment]
I research all day and do this 10 min ago :D
Thnx anyway
